name: Deploy

on:
  workflow_run:
    workflows: [Build & test]
    types:
      - completed

jobs:
  create_release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: gh release create ${{ github.event.workflow_run.head_branch }}
  